# Generated by Django 5.0.4 on 2024-04-17 10:01

import django.db.models.deletion
import teacher.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predmet', '0002_alter_predmet_title'),
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(upload_to=teacher.models.generate_unique_filename, verbose_name='Сүрөтү'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Кошулган убакыт'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='Телефон номери'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='predmet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predmet.predmet', verbose_name='Предмет тандоо'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Мугалимдер'),
        ),
    ]
