# Generated by Django 5.0.4 on 2024-04-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_avatar_alter_teacher_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Мугалим', 'verbose_name_plural': 'Мугалимдер'},
        ),
    ]
