# Generated by Django 5.0.4 on 2024-04-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_docteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docteacher',
            name='description',
            field=models.TextField(default='Маалымат', null=True, verbose_name='Кошумча маалымат'),
        ),
        migrations.AlterField(
            model_name='docteacher',
            name='title',
            field=models.CharField(default='Тема', max_length=100, verbose_name='Тема'),
        ),
    ]
