# Generated by Django 5.0.4 on 2024-04-22 17:22

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(blank=True, null=True, upload_to=news.models.generate_unique_filename, verbose_name='Документ')),
                ('image', models.ImageField(blank=True, null=True, upload_to=news.models.generate_unique_filename, verbose_name='Cүрөт')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тема')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Кошумча маалымат')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Жаңылык',
                'verbose_name_plural': 'Жаңылыктар',
            },
        ),
    ]
