# Generated by Django 5.0.4 on 2024-04-22 17:26

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(default='Маалымат', verbose_name='Кошумча маалымат'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to=news.models.generate_unique_filename, verbose_name='Cүрөт'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='Тема', max_length=100, verbose_name='Тема'),
        ),
    ]
