# Generated by Django 5.0.4 on 2024-04-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docchild', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docchild',
            options={'verbose_name': 'Кошумча маалымат', 'verbose_name_plural': 'Окуучу маалыматы'},
        ),
    ]
