# Generated by Django 5.0.4 on 2024-04-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docchild', '0002_alter_docchild_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docchild',
            name='description',
            field=models.TextField(default='Маалымат', verbose_name='Кошумча маалымат'),
        ),
        migrations.AlterField(
            model_name='docchild',
            name='title',
            field=models.CharField(default='Тема', max_length=100, verbose_name='Тема'),
        ),
    ]
