# Generated by Django 5.0.4 on 2024-04-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='title',
            field=models.CharField(max_length=10, unique=True, verbose_name='Класстын аталышы'),
        ),
    ]
