# Generated by Django 5.0.4 on 2024-04-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0002_alter_klass_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klass',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Класстар'},
        ),
    ]
