# Generated by Django 5.0.4 on 2024-04-19 18:55

import children.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klass', '0003_alter_klass_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to=children.models.generate_unique_filename, verbose_name='Сүрөтү')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон номер')),
                ('mother', models.CharField(max_length=100, verbose_name='Апасынын аты-жөнү')),
                ('father', models.CharField(max_length=100, verbose_name='Атасынын аты-жөнү')),
                ('address', models.CharField(max_length=250, verbose_name='Дареги')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Окуучу тандоо')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.klass', verbose_name='Класс тандоо')),
            ],
            options={
                'verbose_name': 'Окуучу',
                'verbose_name_plural': 'Окуучулар',
            },
        ),
    ]
