# Generated by Django 5.0.4 on 2024-04-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predmet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmet',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Предмет аталышы'),
        ),
    ]
