# Generated by Django 5.0.4 on 2024-04-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predmet', '0002_alter_predmet_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predmet',
            options={'verbose_name': 'Передмет', 'verbose_name_plural': 'Предметтер'},
        ),
    ]
