# Generated by Django 5.0.4 on 2024-04-17 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klass', '0003_alter_klass_options'),
        ('teacher', '0003_alter_teacher_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klasssteacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('klass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='klass.klass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'Класс жетечи',
                'verbose_name_plural': 'Класс жетечилер',
            },
        ),
    ]
