# Generated by Django 5.0.6 on 2024-05-22 17:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Главные меню')),
                ('icon', models.ImageField(upload_to='media/%d/', verbose_name='Добавьте иконку для меню')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Содержание')),
            ],
        ),
    ]
