# Generated by Django 5.0.4 on 2024-04-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, unique=True, verbose_name='Аталышы')),
                ('saat', models.TimeField(verbose_name='Сааты')),
            ],
            options={
                'verbose_name': 'Саат',
                'verbose_name_plural': 'Сааттар',
            },
        ),
    ]
