# Generated by Django 5.0.4 on 2024-04-19 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klass', '0003_alter_klass_options'),
        ('predmet', '0003_alter_predmet_options'),
        ('saatar', '0001_initial'),
        ('teacher', '0003_alter_teacher_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raspisanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=20, verbose_name='День недели')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.klass', verbose_name='Класс')),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predmet.predmet', verbose_name='Сабак')),
                ('saat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saatar.saatar', verbose_name='Саат')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher', verbose_name='Мугалим')),
            ],
            options={
                'verbose_name': 'Жадыбал',
                'verbose_name_plural': 'Жадыбалдар',
            },
        ),
    ]
